### ISSUE TITLE
bug:IndentationError

### ISSUE THREAD

**Issue by kN6jq** [volkandindar/agartha#1]
o my ggg
![image](https://user-images.githubusercontent.com/27048404/155993988-fccf513a-73ca-4ac4-a31d-5a4c77be9723.png)
![image](https://user-images.githubusercontent.com/27048404/155994067-f6bb7cd1-d074-4abc-bcc7-342fdb724d83.png)
please fix it

**Comment by volkandindar** [comment]
thanks, its done!
