### ISSUE TITLE
About Adding New Feature(XSS,SSRF)

### ISSUE THREAD

**Issue by secfb** [volkandindar/agartha#4]
You made a really nice tool. Can you add features in SSRF and XSS?

**Comment by volkandindar** [comment]
Hey there, great point.
I have been thinking about XSS and XXE
and also why not SSRF : )
thank you for your remarks

**Comment by volkandindar** [comment]
Hey there, great point.
I have been thinking about XSS and XXE
and also why not SSRF : )
thank you for your remarks

**Comment by volkandindar** [comment]
Hey there, great point.
I have been thinking about XSS and XXE
and also why not SSRF : )
thank you for your remarks
