### ISSUE TITLE
IBurpExtender' is not defined

### ISSUE THREAD

**Issue by uskolor** [volkandindar/agartha#7]
HI I have some issue when I install agartta in Burp .It is any way fix this .

----------------------------

Traceback (most recent call last):
  File "C:\Users\Joh\AppData\Roaming\BurpSuite\bapps\b4915681326648b1a12e4059d71bc909\Agartha.py", line 21, in <module>
    class BurpExtender(IBurpExtender, ITab, IMessageEditorController, IContextMenuFactory):
NameError: name 'IBurpExtender' is not defined

**Comment by volkandindar** [comment]
Hey there, When installing Agartha, do you use the BApp Store or manually load the Agartha.py script? 
Additionally, have you encountered similar issues with other Jython add-ons? I’m curious whether this issue is specific to Agartha or if it’s a more general problem.

**Comment by uskolor** [comment]
I do that in Burp .Yes I see some also do not works for store .Now I use beta 2024.7 .And I see Burp remove me all my extension. strange ? ,May be to reduce use memory from my computer. ?
